name: Auto Deploy
on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut
        uses: actions/checkout@v2

      - name: Deploy
        run: echo deploy

  # APIテストのワークフローを呼び出し
  api-test:
    # デプロイ処理完了後にAPIテストを実行する
    needs: deploy
    uses: ./.github/workflows/api_test.yml
    # GitHub Secretsから渡したいシークレット情報
    # secrets:
    #   login_username: ${{ secrets.LOGIN_USERNAME }}
    #   login_password: ${{ secrets.LOGIN_PASSWORD }}
